// app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto, Karla  } from "next/font/google";
import "./globals.css";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "portfolio",
  description: "Generated by create next app",
};

export const karla = Karla({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // pick the weights you’ll use
  variable: "--font-karla",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        {/* Script runs before paint → applies correct theme class immediately */}
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                try {
                  var theme = localStorage.getItem('theme');
                  if (theme === 'light') {
                    document.documentElement.classList.remove('dark');
                  } else {
                    document.documentElement.classList.add('dark');
                  }
                } catch (_) {}
              })();
            `,
          }}
        />
      </head>

      <body
        className={`${geistSans.variable} ${geistMono.variable} ${roboto.variable} ${karla.variable} antialiased  transition-colors duration-800`}
      >
        {/* <ThemeToggle /> */}
        {children}

      </body>
    </html>
  );
}
